apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels: 
        app: flask
    spec: 
      containers:
        - name: flask-container
          image: us-east1-docker.pkg.dev/$PROJECT_ID/videogamerecommendation/flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: shopbot-secrets
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          imagePullPolicy: Always
          image: us-east1-docker.pkg.dev/$PROJECT_ID/videogamerecommendation/react-app:latest
          ports:
            - containerPort: 3000


