apiVersion: v1
kind: Secret
metadata:
  name: shopbot-secrets
type: Opaque
stringData:
  PINECONE_API_KEY: $PINECONE_API_KEY
  PINECONE_DB_INDEX: $PINECONE_DB_INDEX
  GROQ_API_KEY: $GROQ_API_KEY
  HF_TOKEN: $HF_TOKEN
  PINECONE_DB_ENDPOINT: $PINECONE_DB_ENDPOINT
